version: 2
jobs:
  build:
    working_directory: ~/acebook-loungin-lizards
    docker:
      - image: circleci/ruby:2.7.2
        environment:
          PGHOST: localhost
          PGUSER: joannabrigham
          RAILS_ENV: test
      - image: postgres:9.5
        environment:
          POSTGRES_USER: joannabrigham
          POSTGRES_DB: pgapp_test
          POSTGRES_PASSWORD: "password"
    steps:
      - checkout
      # Restore Cached Dependencies
      - type: cache-restore
        name: Restore bundle cache
        key: acebook-loungin-lizards-{{ checksum "Gemfile.lock" }}

      # Bundle install dependencies
      - run: bundle install --path vendor/bundle

      # Cache Dependencies
      - type: cache-save
        name: Store bundle cache
        key: acebook-loungin-lizards-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m
            # Setup the database
      - run: bundle exec rake db:setup
            # Run the tests
      - run: bundle exec rake
        
  deploy:
    docker:
      - image: circleci/ruby:2.7.2
        # auth:
        #   username: mydockerhub-user
        #   password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build # only run deploy-via-git job if the build job has completed
          filters:
            branches:
              only: master # only run deploy-via-git job on master branch
