version: 2
jobs:
  build:
    working_directory: ~/acebook-loungin-lizards
    docker:
      - image: circleci/ruby:2.7.2
        environment:
          PGHOST: localhost
          PGUSER: joannabrigham
          RAILS_ENV: test
      - image: postgres:9.5
        environment:
          POSTGRES_USER: joannabrigham
          POSTGRES_DB: pgapp_test
          POSTGRES_PASSWORD: "password"
    steps:
      - checkout
      # Restore Cached Dependencies
      - type: cache-restore
        name: Restore bundle cache
        key: acebook-loungin-lizards-{{ checksum "Gemfile.lock" }}

      # Bundle install dependencies
      - run: bundle install --path vendor/bundle

      # Cache Dependencies
      - type: cache-save
        name: Store bundle cache
        key: acebook-loungin-lizards-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m
            # Setup the database
      - run: bundle exec rake db:setup
            # Run the tests
      - run: bundle exec rake

        